# NOTE: 请测试 python applications/test_llm_api.py 看大模型是否可以正常调用

defaults:
  - system_config
  - _self_


# 应该是第一天建好的图的global map的位置
load_dir: /data/test/DualMap/output/map_results/hm3d_00829-QaLdnwvtxbs/20260127_194233/global_map

clip_dir: /data/test/DualMap/model/ViT-B-32.pt

# 房间边界定义 [min_x, max_x, min_y, max_y]
# NOTE: 要检查，调整成真实尺寸，现在的数值是初步估计的
room_edges:
  bedroom: [3.60, 10.68, -7.45, -3.36]
  childroom: [5.60, 10.40, -3.50, 1.88]
  livingroom: [-1.80, 5.60, -3.30, 1.80]
  kitchen: [-1.50, 3.70, -7.20, -3.36]


# 房间开阔锚点定义 [x, y]，如果没有找到related 物体，就返回这个点进行转圈recovery
# NOTE: 要检查，调整成真实尺寸，现在的数值是初步估计的
room_anchors:
  bedroom: [7.29, -5.54]
  childroom: [7.88, -1.12]
  livingroom: [4.19, -2.57]
  kitchen: [1.19, -4.83]

api_key: sk-02e28def7b114e3bb8de9b2dc377b608