defaults:
  - system_config
  - _self_


load_dir: /home/tang123/DualMap/output/map_on_oe/20260120_054551/global_map


# 房间边界定义 [min_x, max_x, min_y, max_y]
room_edges:
  bedroom: [1.65, 6.45, -4.4, -0.8]
  studyroom: [1.8, 6.6, 0.7, 3.1]
  livingroom: [-5.0, 1.65, -4.4, 3.1]
  kitchen: [-5.0, 6.6, -4.4, 4]  # IGNORE

room_anchors:
  bedroom: [3.5, -1.5]
  studyroom: [3.5, 1.5]
  livingroom: [-3.5, 1.5] 

api_key: sk-02e28def7b114e3bb8de9b2dc377b608

hazard_yaml_path: /home/tang123/DualMap/config/keepout_bboxes.yaml