# 只面向 query_task_1.py 使用
# 填充房间边界和锚点信息
# NOTE: 请测试 python applications/test_llm_api.py 看大模型是否可以正常调用

defaults:
  - system_config
  - _self_


# 房间锚点定义 [x, y]
# ！！！ 注意实机检查此处锚点坐标是否可以作为房屋锚点！！！
# 此处赋值先和示意图中选定一个点，后续要调整，建议调整后将此处注释删除
room_anchors:
  bedroom: [6.0, -6.0]              # 对应区域：主卧床头桌区域
  childroom: [8.0, -3.5]     # 对应区域：儿童看护  
  kitchen: [2.5, -5.5]     # 对应区域：煤气看护  


api_key: sk-02e28def7b114e3bb8de9b2dc377b608